env:
  browser: true
  es6: true
  node: true
extends:
  - 'plugin:react/recommended'
  - airbnb
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: "babel-eslint"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
rules: {
  "no-console": "off",
  "global-require": "off",
  "import/no-unresolved": "off",
  "import/extensions": "off",
  "import/prefer-default-export": "off",
  "react/jsx-filename-extension": "off",
  "react/prefer-stateless-function": "warn"
}
